### ISSUE TITLE
A podspec for SalesforceHybridSDK

### ISSUE THREAD

**Issue by davidfekke** [forcedotcom/SalesforceMobileSDK-iOS-Specs#18]
I see podspecs for the different libraries for the SalesforceMobileSDK, but I do not see one for the Hybrid library. I am currently developing an app that uses native and hybrid features. It would be nice to have a pod I could use along with the other native pods for this application.

**Comment by bhariharan** [comment]
@davidfekke This can not be easily accomplished because our delivery mechanisms vary for our native and hybrid offerings. We distribute static libs that are used by our hybrid apps. We can't distribute dynamic libs there because `Cordova` is included as a static lib in their generated app and static and dynamic libs don't play so well together. I'd like to take a stab at this sometime in the future though.

**Comment by davidfekke** [comment]
Thanks for the insight Bharath.

**Comment by davidfekke** [comment]
I am wondering if it is even really necessary to use SalesforceHybridSDK lib to display Visual Force Pages and Lightning pages. I built a demo app that uses the native Salesforce SDKs, but it I just used a WKWebView to display aura content based on the following example;

[https://www.terrasky.co.jp/blog/2015/150311_001405.php](https://www.terrasky.co.jp/blog/2015/150311_001405.php)

Obviously you lose the Cordova functionality when you use this approach.

**Comment by bhariharan** [comment]
Using functionality we offer through our `Cordova` plugins is usually the biggest reason to build hybrid apps using `Mobile SDK`.
